# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "usb_storage"
    "usbhid"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/c91b84cf-89cc-464e-85a8-aa7f0ab4cf41";
    fsType = "btrfs";
    options = [ "subvol=root" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/c91b84cf-89cc-464e-85a8-aa7f0ab4cf41";
    fsType = "btrfs";
    options = [ "subvol=home" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/c91b84cf-89cc-464e-85a8-aa7f0ab4cf41";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  fileSystems."/swap" = {
    device = "/dev/disk/by-uuid/c91b84cf-89cc-464e-85a8-aa7f0ab4cf41";
    fsType = "btrfs";
    options = [ "subvol=swap" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/483A-100F";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [
    {
      device = "/swap/swapfile";
      size = 32 * 1024; # Creates an 8GB swap file
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
