attic_secret: ENC[AES256_GCM,data:yV67At8h1uQfNNMU0nkADVXxTPjO0om5kiqroF9KhUn6NajCnJt96UiGO7v45Rq4mpGjnxHXXmVk6HQ6IeugRSawsdA6Ltw3OzBw+oRipJU4220v7PdQjtdS8CVIW8C3TO/Tv6y8pXdGCYAg//bodbwdp4W/qoZ/NcbMQ+K5/L178D+4R/1a9teRGHTqs5BQkWbNuXbE9YFrhMEimhXD3ftnd8DdA7nxgwxITVxuP0352Wcc1JOes63zVOGA1ueK5+Cua0o9+TACLuXBHK2yEJE4Pqg=,iv:G/jYx9FezIsFuCRhnSut6/dkKGgkViAzqjL9fITi9T0=,tag:76wTtQ4IFqiisy8ZYMUgXg==,type:str]
attic_token: ENC[AES256_GCM,data:c3B9rg4Y7ja8mDD7Jc2fM6WQ/YUAhCmugkq1Sr/xW+F5xmoxqrbc7q8FKvvHpmBThmPv4PEHNWmVC4x6UqdXQb/Emiz3GO02VAwP/1wFShgLoA3AsXhA2itYS0ESM6ZcMc47FuF96BrYPpqpMS/vDE4+LVPv0OyHe6XUsOczUQ6AgYOT+8q6QrcJBa/J4Ivv59PjdQ+33rIc0mr/i93Hs2nORSWiLOC/fDol2SNfWSVTCYtY0xEoaB51BqAKR2uXSo1ij/xT469QjxjGWXOinw==,iv:WUVzpdRTMn4WfBo8kjPL0sQhGKPL6CfSNXUWm3FLDVI=,tag:NSEK7r5BezgIbG+RcAjBSw==,type:str]
cloudflare: ENC[AES256_GCM,data:Pklel78jbLm/aKRfg8AMaYVjrS9lXhYrq1kTocE/qhodJvrOjI5vDazERq4+FAPeBJgmS/FrJ6VyTWrcKSSUv90pQqU5adPsBIJz4yLKnjKO5wlPfuu7/oTgGRhXgwRs,iv:ajIm7dB10aVDzfL7npvFLudQsbs2WAtY2/fvjk7NzJY=,tag:JK8E1DzRb+CuydNrh1krfQ==,type:str]
jellyplex_creds: ENC[AES256_GCM,data:JyODs8Kslo4ZNFNS4FLQs1sKWKljWDJ7U8uXZpeFsVWX8aFQebo61yl58/KQ4qtuv1PBOFL5e44G2iPVqC/dbPqoddOYDyjwQEMOPfmp7H/wqsSK,iv:6a+5rFrXTCFMbK06tQ+TZ0S0W2sqJ2HMHvs36ef8cDA=,tag:GIXPGfRkbTFn//SbJPrrCQ==,type:str]
miniflux_creds: ENC[AES256_GCM,data:wW9eabECcE6TFSrgzMbNAfHlOBaqARLbhUC2NSYUxvn2zb7PaU6WOyVNLQHI8K23amna/guX8eu9E4oc48N+PgwkmpkpqniWCwoHn3ftD/aj48o=,iv:D2lw+AHCPSvqZLiob8RbulqNM5mH0feqHRfEOjUo8oY=,tag:g6nG8BPKVafxKgaeaOSvGw==,type:str]
couchdb_admin: ENC[AES256_GCM,data:bhlkqSqrbHOXHsdvsEOQ2LuRhqFCx7iTgiSHogs5t0j/D6Srlpy4OdpNYxRxNfMZx6taPYrAIJbC,iv:I3N+i08oHmd+STkSzKmcE7oDiCcCyrFHQIEIskN7g14=,tag:YtJhLZqt7tHzQ8lBVdAY/A==,type:str]
ts_key: ENC[AES256_GCM,data:RbFH+Ahki+nl4j4xEmqDF3MdWF1xpkG/i/s4YCd2IRozPoYMEscu9cUhNL1db6Wjb1nPfG2C63060j/Sfrg=,iv:UNM044nUcpmhBgTrmNayL13wSqeBBHp3mlK2A2h4zB0=,tag:Mt+41W2HEFmowRAhiynjfQ==,type:str]
vault_unseal: ENC[AES256_GCM,data:Mm18BQ5+bA3Oo48kDjvGlSRnZ04SIavxl3i4eIEDClmSjvqB8kW2pnqfW4wZMaWDSY0RJz53WNnREXmcrqRdorQKKFBCz0iRuUcKadi2FQOr++1Jn44Oz9xZ93t0wM7T9tM6hwYSAWDiYX03O9qsylZ0FB+tfx1Mj9qU7az20+A84E72JUKAyA9bJ3c7vFDEddqg0UNIBCquIPU67PE4rhRDGBY=,iv:16uH+R88U5t3Kt1viWhMuvfk7q8Oqv198zOzqWQotIU=,tag:ZH77LA6OxdzJapeTj8wG0g==,type:str]
zigbee2mqtt.yaml: ENC[AES256_GCM,data:Ov0re5O4XWtTIkHCkGpkGMCU5U3LmERoaQkVK8wUeh49VIGoW8lKr4IUWTlXy6aLSHo97WcBAaNh9yD0RDeZ,iv:0mbIi3TaC27+b4rNfUvlz+S0WfMq6FRLWgXseU0tg+c=,tag:WANGCT9EBWCCSys1fT/vUQ==,type:str]
pushover: ENC[AES256_GCM,data:K7h1jfF+XpsGVE7RA7RSYpQ9+lItcY2C9nD6cy3Dhl4Yby4bdfmZ2T/sxDe4+ZTncC5Q0AbMJchoo9nNlnyG9VWM2Y1LZDdtGx4zaKR+OkaeCxTbDvfued2n0hI7POQATz55weDqALlMJUp62jExZ4AqUpJE+6IDk12Yc0myoQ==,iv:1ENakF+h2Sqri2oOAj7VG5GbwlkuvvVqqCoxDbGFbDU=,tag:oL5agYAAMqiselpp8Sm5Nw==,type:str]
frigate: ENC[AES256_GCM,data:JUdZOPvg5tJpNUwso5jqn8MDrhF5dPXp1mvsTBWFN2vklJ5p5PvgpRaaLxmrBcvjeh2Ox+8kNFEVFxKni9xanNJcr2Zz/w==,iv:JviqtSsoR1h/Sh17dtGPnyfQxorZBFnXXLecyiJe6Ow=,tag:/BEfLnDflrEd45APCJC52g==,type:str]
mosquitto: ENC[AES256_GCM,data:kDf2NHh4ACoHkAzXyAMsetjVknHVaqadqDDKQBw5cbQawuTukWdUhzmORkUODTr9+FhTjLNFwe9srzyeOmqU6BaAEkFujAUjWL9MGbqzCqlAgJv+9Kc43N6w4nheqf1gaou3FuL+hi8BBUPtMnsX+Xs=,iv:wzcbeMpRO8xaOdcLx13XV62YEgWKtYihK22QcjK9VSk=,tag:FDdUIbVDFuoYslZpK9VL1A==,type:str]
attic_pull: ENC[AES256_GCM,data:sextr+Goopj9rKdwndOu63CZGvCLeCWTJROvPYZ7hnFY+v3+AKSZPRNL4dtoLgsk1n82+nzg8ui9Tr7ngFE0+/ppwxow4n/bs3MdnxpTlyrdX9gOcrBy+Bgov6KL60aWtA2nduj0bQ1ZPq97ttWPMeVQq0IMBPYMO09/x28IiVII1Y92BXyOK/GQNnJAz5L1BF2dQRFDvLfn0CktqahXHOKoJesskupG+y2SdDNfjIW7g5kgXu4KtAuyNvIr+hR/xKKYHXmf7GnjRGoQfTL4fwpJeMkyXuZFQyCZCPmW9LSJfmO2uqlIJEVlt6dfxLs=,iv:S2o93OCYJPiEr+gxZLuwKiDP9jhe3Bdz+wpgNGRzpzg=,tag:sW4YEvQn6bvnRFQL8f+juw==,type:str]
paperless_admin: ENC[AES256_GCM,data:9iCM+YvnCUCUeN9yKFPzUPf0aOocMgncoNTuZ6q2O5U=,iv:PSmwHU72N8wA5UbIYdhGnXTRFePoEViI780hq6Vezqg=,tag:XzFXDIK4J64NQgJvGBj1eQ==,type:str]
iodine_password: ENC[AES256_GCM,data:M/Iiufcfv2rkJMdnObl0AcInW9D3m1jF4h34fgZMbNE=,iv:Bo5gc/fjEDI31/6fwl2lgXigrWMtW9xkul92SZEeTyk=,tag:L+ASmUwevHB5faa1Hr1tTA==,type:str]
buildbot_github_app_secret_key: ENC[AES256_GCM,data:xEeRnwje61K414LOxmc+XVq/fQBKuk7+tnhyU0y6qe88fz8y/hu4KSfdZ0R3Crt6noSlp9yr7L0An7C/O3Cbe4WquiHkC8E70thyh7d2zcaBH2qFM0WyFKGHhA01xtLVoMYGz6qE5h5SYGsEV2s2qfIAZlbqTHlQX+pk3YPBfm103nE2fQ0hubFD7VdG3+Fyn9ZZjW1MHacvOyBEG5oN202436N4W7ABvjj+ComT0ng2kspz6R3ndgtSWAtrNfdnty0SnNSRHKlr/Z9CS+IHKEe+9O5IqOVMPqzc8TnUXmoT2cAjFqAWK8pH8tk/F4XiSE8KcfK7V7JPtdaHKG1LJRJ9pk/hAo8BBoTYVtypjmC6AqCOvqy2sujvLVlx1L8zMjra8Z1HP069p/4uU61siWdAyxB/SSyuheMbH0nsjYWb/g8/SUIagJdGaRZSwmC3PUwK0XiTgwcjNz1qo/vhxyFdBcGrZqYcZLcuKe0KI+FmlJA8WQgKLHPOtAwM4XqxNoL3HRo1qnYFx6OehyomCQjvDOugPNufLRI2sDZF5CQZiXsmtkvv/62mmqyCSkTlOgRfLZVJKBsRlmDghcTo8CKjaELbRXQYlSwsDeOcaZc+aPlZSbT2+6tQEIyolPGJkBn8+uVj1LgJrbI3HnosXKXgjC8LETXOEoZ6tl14HzUAqwVBF1gQ28EZj5ivqkk5SpqNEi2YQqBWRYsIxQR7fsMpVBhp0WfXmBMuVsTMckAbhun7o9+a+aMG0opj8x/VZ7GXoF8gpSQbYC4V6mzW56lwcT6/CcawSENsUse0OhAulxNMIRD6a6NyTiThLFZGaV3V1q1nbNGYKlCaiEqWcXtb/48ImK3XkGQG1QxCNhNRrRdaHxeDXesRAg5tCjDoc6+BkQDfW+9v8YNAdlk/ilKI2sSl1TgFEJBZSx6NFmPfQws6iwmq4ZEV4oql0RtdZUHc0uq2jH+sySZdKCRBxIgtSHyuwUQKn27hvy/A7/PIk7tM7luoQuZdnnfpP3xO1nD7t7XYgdLOCEPbjyttcIqG/OCKM9cKf94yYhD7QK9tYHuiRBKVri1sYvP0c/gDnAiJe6+d0irNug8UZ2z7pVILZKFD4h24gmaPSb2+hYS3xCLMEEn4nTlhEagQTAoh+FmSD5quWf9rEAIlRduihBSmcCausAGmLu9I5jLLxO9mkmO05erIR0ifF8d66AsY1niEEhpbavMRu0Yf+WRvPY5uHtD9CROEpBoy4ug1HwaLEKKkMIlT+Ln5Fj64jLeeXYKPNY5ce+X72F1yegkqo4m3Ta5bnmuxv142HGP5R2YS2dycNxp0tVshMlk4nkXmo9ooI74gCJUYfCQUwSBC8VBzEEUv1ipBKsxkY95U7qAB1v6Ue5J3gGq7SK2zR0woPv7aAL6IDJWb7fB+3/nvZvvhRgoVx/FnBPTODdOOmjjlFF7t9yc0PxcH4eMT5KISajY5TriqSCa1qY4eZdupvlqCv4dosoDGszD3lpvYkeEL6mON2yMuMTWhvYk2GbP1Ih1vuHScPw27kZPeVQCjA/ReQxqrMUT1G8ZvlKmRivrTTcQYNZdpmXvjKs/+EtPRnKsr3keHWuZ2vdab3dbuM9Em4xrwj4DIYDWBlPwChwp3C/HTNlmgNdqJjtBmnLAo2wu/rr70derfYkcnxJuL4h5LJKCGcgbsiWD2kORV8Fw8BnPTzAOlY3py64xOUKLQgoNwhhmv7rggNMNsa2LCvqW0un0lng5I6QFzVWGQImuEkngQu/8T8E6lyxbw5yLY4Fguax2ZkX6OQa5cfh4o7DyA0Tba9kKEX7CYpiVqeaueIobe+WRYk0e1Kit4JorFIa66sXUJ+fn2wdmFEyGhafbR5ZIgtj5dYkJX01GcQYe4jwHd1RBSI4dc+cddT/F+LBvqxPOzhtYe5HW3ypy2XaTc3ThePzegQ23nbP0SqPtqvXxFMsaZZGacIjq1zmKoKSZGq9smDOmmQXnnbgvCWeRqDMpyQd527l9vB7/XJdS45LWotdk/h5/Ffc0vdK9F00eojMbAEVebFxZxphWcMR87kgvaONsUsRCFGXaTjCwKkwEL5iIsnYDACE3tecjKuDVg1/s7S7rcvtGSs9v6ARIeOw69LkhVZuOSHeEMOHMUJ0XSxs+AQypaVkzuZwGZgQDL6vNaleOTAlkkg53r7R5vHtY1ubJPKEapzSbC5TX5Y6GihLmJDhHP0w==,iv:4iCVH1HfO1RaT2+AK9vsntjvJDnLF1/hb3ozNSCyeHA=,tag:IMFHURhtiA9fxV0nM9YCjg==,type:str]
buildbot_github_oauth_secret: ENC[AES256_GCM,data:TDJpkxJttst4dXaqjcPtLNtaNtFyUJlebdbdOZx/Jo4xMUEkGPOywQ==,iv:l/hj3h8IWDtxHVXE0hUUZJZDrs9NuNf9ivuTnbNOpyA=,tag:AM6XUrIz+S0DiNzNX+eoHg==,type:str]
buildbot_github_webhook_secret: ENC[AES256_GCM,data:stC8t4uCNTqs/V5vxWB6yhBxUZRwl2zuS0FAxSd2yFI=,iv:CghpJVOx0fWXkwiBfVII8+G6T3CmFA6KAnRL5q2UTjM=,tag:3FjsYNuNE0L2XUhjAgtwTA==,type:str]
buildbot_nix_worker_password: ENC[AES256_GCM,data:4vO5PbQg9spqZkezjiI+FlIfruXlZipao5zV1cBJUAs=,iv:NagAjzUYxWkD22Dx1Xd+94+SJ3i0/g5Ljl438JO407I=,tag:56vbpDqNeyatnNxHEYis2w==,type:str]
buildbot_nix_workers: ENC[AES256_GCM,data:/+LPeYdPSm6un4Nkklp4qvJUua5mHoCQExY2eGUoSL9ktiJg3zwrw4olZ927pqIbkWbjFs8ZuKLMVUNu/d9PfQ7QHEbRdxFDcGFq/qz44oobSyq9,iv:AOSHbkKj79/tQz5xowcMm6Hmd+hyWHiS+4fSW/nDESc=,tag:8jG6DRcRQm7b8tD2caNLKw==,type:str]
authentik: ENC[AES256_GCM,data:VXmVUSI0rt4qE1SS8m4sPpoHgiq0O+XHn5X7XsliJO2349p98XrFpxsAcql9EjS8dVNonpJoD76HoHk/xJu9C5c2a6yteeOLvZanFd0HJUYZqaK7YjWLqoro+X72Zk5Ai36ELbWZ,iv:UYqb98B2yp2KFkSWETpWIJLOZeR/xMe3QsRyUepNb1o=,tag:nFtJwGuNQxVBeI9A2ca5zA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m97ls72xcy8v492xrru4keyjve0jcqytqne6jk62zl72j3xsqgrql0ckw2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArR0kvbjlmbmdzSHYzTjFI
            czVIMm5zTFE1c1F3a01VS2lyYlpEL0JOaUZZCk8wWTQvbGJhTXk5L2pYQVNiSTdl
            MUFDaS9LUGQ2c0FTQmRXUFlFbHVHK3cKLS0tIGxqOUxHR2hieFNyb3BGMHJvakg4
            b2hjZUtMcVNseFIwNDNGM1B4L0F5QTAKOtxovamTfUF16YSyPaSh8N9WIl4u+tpx
            3VenfS4JVXpw88rF7DpjXYccpNTrhq2vndOykI6A71P29l0b2Bba5g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mwrrymv9hsyhk3vtr5gqnhqg76rsh4f4gjpr5d3rg966lze6lc8s8x4z20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZVFsdnkyQ2FTbzhLLzR3
            WWkzV3g2Y0g4TlUwWE5lOWtqTjNtZFRIRUR3CmphRmMvYWZvYXZvUFRrTWVCeVFB
            VGs5dlBEaVkwZ3B4L3ZLYkRWK1pZVlEKLS0tIE5OZUQyWko3QTRENHJ0bEw3WWdy
            UkNrelV6dmNzUXpqcmk5TE41a3k0d1UKOM16GIuRFfL4OADhuMYPC2x2NfhEV8Cj
            hQpJg8112Spvk4LAJlUxF4qqfSvyJxxlPSRwlibyFPozuzB74uRkJQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1klyhch983y7as7xnceltplys58lhmpu3w0qpy5gf0nmay6fjhadspml7nf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6LzdyZWlHanJXY05oTENQ
            UXFtb29pSDZPME1kTEo3TVN5THkwejQ2TGpzCnZVNDNqYWJzT1B2SHRoMjU0amhY
            UHFSNTNkS3RKZ3AyVExmZDVqR3pJNlEKLS0tIElxNDVPMVRpR0xIVWIwY3ZLeHB2
            WVI5cjFhS2twd2FEZkEyOHZIVk1RSlEKWXKhEmWhH6oiRUmUIFvh0V5SFtycphUP
            btINPrXn7eef8MBtgvw5rOA3BDw4dLXteMZm9/MliNeTiZM7HNGOSw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1swcq9xcguv3t2tgna80hewemc7yg0cdgyjff86q0d6gj24j8xuzshl2pdy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUm9Pc25ZU2J6azN5dEtX
            b2pkTUlWTmd2REpWSmdvRkFQZ05MZmtmRDB3CmZFN1luSEFIbHJBM2ZJblUwT1VT
            cU5CWXpUaTNUdm8zZDF0bGxlODM1MVUKLS0tIEVoVHRlRVBJblVVeC9jaC9xL0ho
            ZHNzaW9UOUxlRHEzb0pTUmxPN0VBYUEKqWEIdUxl0Q8GcIWa+kU0S0ubaC3R67CH
            0BPWHs2EUY4DZevCGq+rFd90Fmx0tt9HkfdioH602w4n3xi1DH6ilA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zr8jlq26nmm9v9heg2tv5gym87ctk7ry67x32zfux43ta75mrfkqmj748g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUDNIWThuYnJieGpOcXVk
            enR1NXc0c1dQVktEWC9WRDU2b2pLZjJvUHpFCmZqRmwzS1hHL2R1TFQvY2E0bDlC
            WGNXMXdTQWJQMkk0SThxZ3hhYzZ3MGsKLS0tIFpkSi9ndTR6Z1l5VXZ1M1VZK1Ax
            MXZEc01QTXRUVFg5Y05uRGc2Y01jc28Kj41kakNgtkb12dVb1X7jBz7uRGWWFM/3
            LRCfKWbug/g19XgBeueJbwqBBO/Qhcr4lTQhHdQBEaXEyRIKU1sb7A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dkzr6l9t3nx4j0vhk4nwce6f9836gfhx35xr8hnu9qxp36mt6esstlful7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRU0JDbVNNK25TRmZYenVv
            RmRLV21sQVM0WTRnN2FLYjZpRXRDd3hvMFNzCmtucUlLTktMUTVkUHl2elFKTEZs
            RnNYOE13N3FpSDA0bjYvUXJpMGExVGsKLS0tIDZhZm8xcytFWGJkS0EweG9ndThR
            dkxZRmJlZ0s0V3VkZ0xWbjdLTjdMd3cKTjKxu5pZ5Y+ivKoUvUeaUw2Oe4MHZFYr
            dYM2v/O9x1naa0uBch59ONtYj52ry0Loy12dEsDihdEWLHVFz7NTmA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19wl9469xemumue4fentzp7pyh97tddcp85lh7jsm5vdm3asw7qlsd0rqze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNS9LZ0pTdVhBWCtwWXVu
            VHRrU3Z3TlV1MUd0SmV5R3FaSkFFS3o0WW53CnNQZ2VONXVicGw2Zjc1aTYvbjBI
            N0VweDFmSkN0NGJRaGNZR2FSODl0dzQKLS0tIEtxUDJyemxTb1dYeEs5RWZtMHhU
            UDFUMGdVODVvVTFKbmNUc3Vab3BZY1kKH5cpXW5v+vJJSyqUaX1+Wy8ILdcwwa1Z
            SKeu872RnVfl2T2zniDBf5Mlm4R18/Ofbw7XNbUYAthcTup5wmFBUQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18xa36s9536dz0m8knmu7nqndk5g6eqlsphn7f2226zc52s5wcphsg5k0k9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZWFLeTUxYmZKVTlyQWZy
            T010T01BbnM4ak1JZ0wxNStTK3FEaU9GZlhVClFLeERpcVRuNjFQMVNXVXhUSzk1
            Z3F1T0NiU2l2cm1RL2diOTlOV1ZYN0EKLS0tIFZWWUZDaUx3TUhZZmVMR3VSU1hM
            SityNUdINUJVVkFiTCtyc1N2N3Iwd1EK/FzX67aQhy0iIljiN6Wa+5TOXE7FmvRT
            Kd1sZGvvENiGoKb9sfKYhLMibdqLSSSqLzGh0CM3YXSqoBdESaUdXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-25T21:15:43Z"
    mac: ENC[AES256_GCM,data:L7BkfZaQi4eQaqxec13Y5qSKTbbxCKrm2G67FO4CpUoMC32EGS86Sc14RM/ybvXD3SesU+sFRQCKR/KYUSFk48ENV7VcpGn/p8GQEwU8d7o3z90vXx3E0U3vu8LU1siQdXWLkydscwmF0fTjabSHlEmxBvMwOR6/lYZ21Ne59m0=,iv:0ljpxJWRFMk2aFkggUXtOlOmAZ0F1dRF7zVEggt9fCk=,tag:ZgZmFZcWbIMt0lPKcsCjow==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.3
