attic_secret: ENC[AES256_GCM,data:nT00K9ncLn92VgNLvpgsb+vkGn45K7Mr1iDrJOhHV/pgOKj0CTnUuc9QYADPrHvbfaBXOzKarPCqfxwRB1Q5KbRd5hVF8MRCxAPl772Y8RICdXuzd2Pvv0XMgUj+L/ikoopnyFTxPkq/ZPhPBbbC+kbakh5fKJNxPGuklKdM8Yx5zL/2/HP0DzZNp67gb/n9AiS0rRHyB2hvycNF7nFZX1mZjftwEZrcPyfrxlbEYqC1VlUbamaodgcQcX4IS+4fJSbz2o0SzTetVhcy+EaHxICLWfk=,iv:mkoYjnAmLcvEojcCqCuVc58tUuiZyM2fPMMAgRa8WAQ=,tag:mvIYmiWq6hWZcLO+eFo1bw==,type:str]
cloudflare: ENC[AES256_GCM,data:zDXOn3TMniWzblA1NvhR3GcBbmmpTb+ubiMUp9l1XaeaTWhIIJGuPOnW7yemDX2WM4TA+vB2KNU+USf217l8UZGehEwaA1t73lszqiu2/vaM9V57s7abOIIDvekQnm4D,iv:TJQK7EV4gGuFkgSIaXBhSJw9fnKu8lbiSAt449nlndA=,tag:mVj5Q2UTl0c6kDwTyaQFqw==,type:str]
jellyplex_creds: ENC[AES256_GCM,data:bLND4DKrVrVUO9aN0viHfQ2o6JbCHidQE+mpl//w18961HhPtUeVuQkLhKUWEskjOqJtHJ+Z/xerfy4p0aNkUjnK53LL25l7y5Lq6LaPzR6/n0RD,iv:4z/jc/bExeoyVF8NB+di2q+7pjR4I/cgYmFH7E3O7zs=,tag:b6iqUC1117sLavvHtgR3Dw==,type:str]
miniflux_creds: ENC[AES256_GCM,data:mnuI228f3YkEKNEnI3yRO/LHqWEprby2RfCtptF1dhCmdql7ydZt8jGpfBXV2+4LqTlUSOjS8qh35CGBed70uoRjcujoQJTdX3VxzfKQl0zqLbQ=,iv:qPhuGKkAPVLD5KNbFHsboCSmGKnwLNd7+9awnwKIO2g=,tag:ecDN0V8bCsYIF7e0pOec+g==,type:str]
couchdb_admin: ENC[AES256_GCM,data:K2k8V6O9mWUBKG6ykTzdgiegWaGtrL3sZkFWG024p0ozvOqYQ04LOvR6kXnNx89eM2v6ATVb8P1a,iv:ZlNSnciZ6EddGk4wfzocqqPwvHHkyaDF3KVJ8l+O3Ow=,tag:5rjMf/WOU9c0rsVxf8Kckw==,type:str]
ts_key: ENC[AES256_GCM,data:i/PIgPiXJCywVaiisx6hdgaNC+n/FrJODSHEqtNcR2WfhKyjyS+8JdNh+QHwk/Jq5X9aa3gTaf0=,iv:lRMdORNir05RAWrGoWtV+b9mUqONyldHFktNP6qF+78=,tag:GxA8fDlIJbD8nadvR4Vbyw==,type:str]
vault_unseal: ENC[AES256_GCM,data:S5Ir2/1nefoLaaZIQaNjkHbFnDejVu3HJSD0oeUF18a1moQNF4ITqUOONkp391qATzPBp2nccf9tnMjZgLs8lyBrol4t/OhUOXD1nxncXTDcA8xFz5Si1RiBMdemCR6LYF1P1DoFHiA3M/1QofsmEAAiw4uVDu9BL0O7dOrE1sGG7Grky3bpVAbFlEpbnwmx6F/YQlZz1JqIwAojLWD9PUwgTds=,iv:zy42IGwaHu7FVudLya8fwMd2cnKUroaUu9mG5Kai+5M=,tag:R1zk+ULIhcn4SorFC2+NCA==,type:str]
zigbee2mqtt.yaml: ENC[AES256_GCM,data:2guN4OD+rDOiduPt5cGXnLDhdIq0M/1bIhcXwHv7uNZp4hFsVOnk/YfCF7+s0UlceNLR39AGYyc8AzUBdcw+aGQA3dJksLk+2QNHkooqIZERgMDyyXb6o2Ll7EzF,iv:BvyxqkGCSIhW8E6XQyT0ZP0bDolFW4xDQd/Xb10+NGo=,tag:cp6aaULtC3hRTWco9uju+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m97ls72xcy8v492xrru4keyjve0jcqytqne6jk62zl72j3xsqgrql0ckw2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVGVhMTJYcnZtOEVWc0pu
            UVcxcjRSVDVwcnl0TVJBRm1OVmxBMFl2cFhVCkV5dUQxVW5GejcyUERqN0NMdCtF
            T1B5TSsxaWlaV2Z4OCtGbkh5Vmp0U0UKLS0tIE0zczZBTTRtVGY1SG1Taml2Y0kr
            OGF4aTRSWER2NWZtdW1ZQmU0ZTZjNUEKYRoDPm1BPD3bsyasBA8ogxanK1Cn7agX
            L2zxEzMV/TM/s6H8m8emuSAHfMjJNgqfCXst//ooC7oKRK56oZWxJw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1c4zgcemg330ajaekh23c9v97ehv78auy338dr0tf06hst4p00g5scjlgah
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaE9IOGRoYlZENzhRK1c4
            Mm8yaGFPd29ydzJZRWRpSzhhL25tZDAzNGxNClM5eWF0YXZFc0ExSWY0K2RoVGp5
            UmY3SGlYZW5Tem1VT2twNXRNMVBFaDgKLS0tIDllQk9hNURheUYzK0lGb25HdXh6
            dXZINm1kazU4VW1FNkdtSkZIcTIvN0EKiGWAtgm35/o+KvbUoXewPzPI3b7OXO2p
            sLFxc9ik8EWhngZ6QsmFYQn3hx5fyNT046dMPchQ7GvOhwRNEbo5AA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hdpn83swtm7rr4ex4x6kh9k3ffqq23qug9n0ztq8wgaqlu02xekqku588k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHbFFvQmswLzdLZVFEK1px
            RUJxZFhGNG9sZDhBWlBjZDlldjV4c1hDMVdRCjJyaStITXEvU0tNVG1NUzdEZEY0
            Ny9RUWVEYnhBbVRZT0NvMm8wcGVONjAKLS0tIEcralZlS1I0K216MWl1Rm14bXBV
            ZG1vWmpKQmlHMTR2NWxldzBzUkUvWVEKwwtb96EXMcH4Nwv1n+APsmeYTZ8hM4sN
            pUykYbVq2U4fHFt7QS4jFKvwsPk5J5Z7toMzEap1BnDAA9+nvj8zOw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age102uzctt5y5qgqn9tz0njv0uh3f8yc7ssr3y8uxc3gd2n4lvu35es66euf4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbTZVNlBxSEN2ekljcElN
            NHpwL2hGNEZnRllTdFRYZHo5ZmQ2bE40OUFRClY1bXZldk1SUVBRakZZYmJpcmRq
            enFoN3VvZ1hsczFUaVpRY2t3aWp1aVEKLS0tIHB5SUJNZGgvTUdHVFdQb3cwZTVX
            Q3ZSQ0YwdW9zL0pmUDNnQVI5K0liMzQKAD4WlzrfZWkCCuWrb6PtftDs4yVegwiG
            nZWoirmPOyPVU+Gn2o5SYouqR1NO4RyxuqHatBZf3/231jh+mJ21BA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zmye9v3dmws9vtvkm8gfgknedggql0hnl74k427wqup9d0rq3esqfgthua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVXJyMmNqSnJUZ3RoTi9r
            UTkyZjVxZE54SWtpN1hSWFlYZVhJYmQzOTNVCnVNcmQrVmJLeWJxUGlpb1dyQXVq
            YjBQSEp6bDlTUmZoSWdEbTV5cyszeFUKLS0tIEJNb0pJUmxkSk5sN1Y5ZW1JMmxs
            THZ1aFpPTG0wRlcrWEZQaEtqbXhaL1kKvmMcUUBL9YcJGZW+AHjgKexFiijwPBwr
            wuFWob0j6/K8CiTBOC2JGvgaCMyFgZf7+TWktxoZqqQkWvMxkB48Zg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mwrrymv9hsyhk3vtr5gqnhqg76rsh4f4gjpr5d3rg966lze6lc8s8x4z20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZGxHRXZpc2pzb3R4SjJ0
            QXQ5RkN4bmFPVWd3S0hQNitUa0x0enFHQ1Y0CkxMZFlCQkxYd0FEUGRheVg4ZzNi
            U3YyYjMvM0Vyd05GYWRQMUhrekp3eVUKLS0tIG8yL0JnMTBhRjFiNDZ2WVF6anpm
            KzB4cStraGVPTTI1QnFyV2NFaC9Kd0EKcX0FkDjaQAe1z7cb3b8+E64mQbvYhvjX
            4qclU5yWOOdOeHFCTP3epiTSfmXJuyjcvbsCm8QkJwxiWN8FsstjiA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1npj84lxnq72ppch90k7fw62wwy3wq90c03hy7r596m3yvyevd4sqlqma6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUkJraExoOUF3VDIyY1dj
            clJva2oyTWllaktDTWRRaUFCd05CNHBidGlzCjg2aE10WnpSK2dQbERVWDZSVHJ1
            cXpLU1pSZnMxdnEyd0FXUlgvdTIwNW8KLS0tIEswSWZOZXlRNW5ZMzRtd1JpVG9Q
            bmIvRzAxU0RFelBlMGZXMWEyWUVnR2sKa0vVV6CBmZqmOe0gjnsvzYbeTeDBSWnb
            nS/uNE4nEWMv8j7NFfL9qK7NGQ1xiYNWp8vW2yG2Iv4ce21Qkhz0nw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1v808y4su2d9yehped4mahc2cgs56x9eeg7kgcwltg9k0vgqx8vxqrymgh3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbTlObFhVaFFXdWNZdWVs
            R0ptSGgvNTErNGNicWdwRzZQWDA1L1YvdW5rCkNNVGtBVUpOSnFHQVVCY2FFSGRN
            T29QTCs0NGFTRnZqdlR3SitxbXFuT1UKLS0tIEpqLzJ2a25oVU90Zy9QMUVCZEZy
            RnlTbEdiYVpkNEVQVVpKNnM4LysvWXcKUgIqh6ArBcvB17Jz8mqm4h0D/Hn1n8Lv
            XVt1rnyygteyjMZMrcdPxEKCQhVoTy1OH1of/jlNSsiyEGGlVB+4pA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1p2au0z6k7fnca8pl3p8px4ckt676ap43x78ud89ew5dux7p6r4yqhyqe6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByS0JEUzMrZzAzaE9UMVdC
            dUhpbmxxM3J5cmJiQ21lbTVIcDFIQXlPRUhVCmpkTEpFZ0NpVWs4S2pYYXVhT3gx
            Nmp0UVFDNzhyM1J2TmhacWplRVQ2ZU0KLS0tIFlSRllhcUlieU9vQkV6aUdsbFlC
            THRvUExnVjVkM3dRRk0wVW5DbjZ2WmMKYD8nt0z+xzWAXuXlhmc03u9XKdDEAKDq
            Ry7Cb7pPr2EsSc8cURy5TLp3ZI0D8kxmrKf/fiafOSaq2AfOlds/Lw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age150kczuryvnf82cfwdrph7tekxctmwe2nnhmefw7gs6f6sl4n53ts5d7yve
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNm5oOXhJUHljVUhVZnJT
            STB0YmYwVENlS0thZEJQNHJzc1dIRlB4V1FrClZuVmpON3ZtNGNHNnFKOFhCRU9h
            QnZidmd6Tzdrd2oxeVdaMTIyemtiajAKLS0tIFBLUW1TRGd1b0hHZHlCMnpmRVZ2
            YVdaNkF1T1duVnUyL0lCYTUxdExBRjQKAS4T5/Zhw8Hj32ebksRq4eUndYz/LgM+
            ibnii4+jcxMHMyfDOpKzA+I+KPrhEYRklWX+3zNmlORqcJCMoi61sg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1klyhch983y7as7xnceltplys58lhmpu3w0qpy5gf0nmay6fjhadspml7nf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYW1PalpOMENtMnNzNFll
            UU1IVVM1cXo3UkhrTnIvWm5WeTVCMGx0cjNZClU3SXUxVExyS211WkhRbFBqcEda
            WU1kaGtsZWx0Qk5lQlo4b2NLM2NYdUUKLS0tIGprUHd4cytRZG1QOHhJNHJubTBk
            M2pVRVBLMnpIbndHcU5OazU3bHYzWjgKMuCmScjQVit3tsKAAMj9eG1TwxRp/Aw/
            cYf9GgCycCd3GUiD4h3H8lqNDNQ5bPmTn8iCWQMjQiSCYUgz8Xymow==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zr8jlq26nmm9v9heg2tv5gym87ctk7ry67x32zfux43ta75mrfkqmj748g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTDJOSWt0cUltMk1xaDBs
            RS85bk9oaWpwVDNHSmd4NFNraWF2UEZtQjFzCjUxNnVJdWc2YkRiTlNiRVBsNkFN
            UnZ2MnFpYkN3MlV4MjdqYTZtQTRwSWsKLS0tIHoxM2FhKzFGZ3JRSyttZ1laTlVE
            czhwMmEranlDQzNKZFF5Mi9GaStoMnMKdusd2x/sKkL7yOfqLsxWBtpLKN0C4LJB
            uqlw9mAoe7hpFC04oG8hr4SGEHfRMXoxgz7cWXwubLoReGDZcFTQQQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19e4mghy3fh2ejz64hc7038t5thjddwk5rjlad4wekg35cvyy5ses2ve9q8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsamJSbWR4WVBMRlpTaGh0
            UXd3TU1za3RIMUxUQVA2bEtPSno0dGEvTWxnCmJzS3gvOVRRZW5EeVUzS2FiYXlC
            blJwS2lSTEg3MzQ2Y3NXOWRhTGdhSUkKLS0tIExXa1o3QWRhYmM4emNYVmpTUnBU
            TGZ6ZWx3TlMyMFVWVkR4Um5FbUhaVEkKiWykL4anitMMMOkdxC7ghPd58ItUUL5d
            WGPOOgH9j9+dudplBv3avQJX8bLVqo1Hy5tTJxY3/h7HcoVnEAkp4A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18jr3phuw28jkmhxg220nnvp5sev6fs623uxylhnmfsed73tg5pvqzmydem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMaDd6YmhBeFlJcXlTYlFi
            SWNId2M3Zk84ZloxS0RuRytXc2VGMXlrNURjClc4Z3VrTndNOXVlcEFoMldNL25t
            TjgvTXdwWGVjVjlwcW1XdE5PU0Z3OUEKLS0tIFpZaW9XNzdrYk5XaTRBa1l3M1Bq
            RzVHMDVCTlBGT2dCWXc3bUxBNVlmNVkKevNgHtsVi0zn3AF0Oj2QpWzXvWievOxx
            dfi2tTPKTjZoLyl3Cpe6vEo+0pHeTNBGQd8JF+DuH9Gnka91j5jfOw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1fcul2dn079vuw4jghlhyv075fq6qg3fmvkgdyaq3u2chwu3c3dqqw44hcn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQ1ZHZFh5SDd2QWhEUjNz
            RmoxRmdSdDljdEc3RWl2Z2tTanFhbXN3Y3o4CmltRTA1SnFwcFFyVkJYZXZUQTZq
            dmZYZ3EwTjlTTlJteFBrVWhZQTRZM2sKLS0tIFFPSGg2QitQL2Nuc1dNVFQ3UzFC
            cUlSei9DQzZGUDJrU25WNGVGT3UwZEUKg86KFGZECyJulM54ByhlwlgT5GD7QkZa
            vd9MO2tYw0WjeSPcMrAj1kCrZjdUQ5pWNZ8Mi4OAw36AeGathk9AoA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jxrv4vph55036gczwjulu4t0wp7tzacxtcjv9wfrve4fps3w7p2sds32s3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRUNOaGRDQkJjRkNqeHhZ
            WFpDazdUR2JWRE9xTkJibWtGS3BVd0l6MmhnCll3MENtVXZaa29pS3AzY0lrbU5a
            dHFGY29mMGU4L1dYd2tybDR2cWY5RGMKLS0tIGxleWlFbjJVZ0pnK3RBcjU1R0hV
            V3R4Qy9ORGg5Yk04dks3K0ZxOTk2OEkKu5uPG09aNyFnhyGb81FaFgBm22KpT0fi
            0f82lOl9zYPHxGCysRPeqBo0+Ewf0GQPzW3ZlAhI1t8XwErY04AozA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1swykyyzngx7zs4ttt6t32ru8yfg3gq3gamfc4ywzdwfdnjn5fqesxqk440
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZUhVYi9ydFJCRHQrM0Rj
            RlNIK09maEZ5NmwrcXNwL3pPV21HenF3UlFBCjRrOGhTcEhLNEhSZXJyaHJwaEVV
            YUtKR3ByaFVINVlPUUcySHRFUGIweWsKLS0tIGtYSVNqaVd5MVZSNHlTRXhrcWFC
            bzRVK3kwb3p6QzREZUhEZGxuNFB2eTgKhTCGktXau6iyMJ1bruejk/pEtKbKivTc
            QxmqflNdzumlhZ8R5QknUMYzZyoBojbOsj6Cg4fAmN4AElPSO9FPvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-05T04:44:53Z"
    mac: ENC[AES256_GCM,data:Zfpb7TcgzZ0poBsFTIbQwSG9wQ2gNKUWNNhR65puGh0+MEnXmNfCBDx4r2a3ZqjFZUJrsC4TAZCfMuKYsyc8P3mTAqESRzcfTQsR4ACEBAIAOlpIEPaJjryciDMGR131w2l1Ynf5MOLTo+gniMznwRI89IcMgz1f58F8R4+K61w=,iv:ZfMK7nbAEafmaBDeWPXKMF+riJkoskoiclANGUoXx1c=,tag:apuEB3iHl8KqwGHmEKRizQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
