attic_secret: ENC[AES256_GCM,data:yV67At8h1uQfNNMU0nkADVXxTPjO0om5kiqroF9KhUn6NajCnJt96UiGO7v45Rq4mpGjnxHXXmVk6HQ6IeugRSawsdA6Ltw3OzBw+oRipJU4220v7PdQjtdS8CVIW8C3TO/Tv6y8pXdGCYAg//bodbwdp4W/qoZ/NcbMQ+K5/L178D+4R/1a9teRGHTqs5BQkWbNuXbE9YFrhMEimhXD3ftnd8DdA7nxgwxITVxuP0352Wcc1JOes63zVOGA1ueK5+Cua0o9+TACLuXBHK2yEJE4Pqg=,iv:G/jYx9FezIsFuCRhnSut6/dkKGgkViAzqjL9fITi9T0=,tag:76wTtQ4IFqiisy8ZYMUgXg==,type:str]
cloudflare: ENC[AES256_GCM,data:Pklel78jbLm/aKRfg8AMaYVjrS9lXhYrq1kTocE/qhodJvrOjI5vDazERq4+FAPeBJgmS/FrJ6VyTWrcKSSUv90pQqU5adPsBIJz4yLKnjKO5wlPfuu7/oTgGRhXgwRs,iv:ajIm7dB10aVDzfL7npvFLudQsbs2WAtY2/fvjk7NzJY=,tag:JK8E1DzRb+CuydNrh1krfQ==,type:str]
jellyplex_creds: ENC[AES256_GCM,data:JyODs8Kslo4ZNFNS4FLQs1sKWKljWDJ7U8uXZpeFsVWX8aFQebo61yl58/KQ4qtuv1PBOFL5e44G2iPVqC/dbPqoddOYDyjwQEMOPfmp7H/wqsSK,iv:6a+5rFrXTCFMbK06tQ+TZ0S0W2sqJ2HMHvs36ef8cDA=,tag:GIXPGfRkbTFn//SbJPrrCQ==,type:str]
miniflux_creds: ENC[AES256_GCM,data:wW9eabECcE6TFSrgzMbNAfHlOBaqARLbhUC2NSYUxvn2zb7PaU6WOyVNLQHI8K23amna/guX8eu9E4oc48N+PgwkmpkpqniWCwoHn3ftD/aj48o=,iv:D2lw+AHCPSvqZLiob8RbulqNM5mH0feqHRfEOjUo8oY=,tag:g6nG8BPKVafxKgaeaOSvGw==,type:str]
couchdb_admin: ENC[AES256_GCM,data:bhlkqSqrbHOXHsdvsEOQ2LuRhqFCx7iTgiSHogs5t0j/D6Srlpy4OdpNYxRxNfMZx6taPYrAIJbC,iv:I3N+i08oHmd+STkSzKmcE7oDiCcCyrFHQIEIskN7g14=,tag:YtJhLZqt7tHzQ8lBVdAY/A==,type:str]
ts_key: ENC[AES256_GCM,data:9Por9DsQTsopx7kh1IrYOK7BLD6kRhRLr8I9kpOgq0oRUXo4j3AJCgekvGUbfX6peXYZW5BS6/U=,iv:TUhmx2j0mZlxw5aTFALlZhGdNClStqOTe/mp1n7mIAY=,tag:gv1m2hjWFDCLXGJ2tuM9bg==,type:str]
vault_unseal: ENC[AES256_GCM,data:Mm18BQ5+bA3Oo48kDjvGlSRnZ04SIavxl3i4eIEDClmSjvqB8kW2pnqfW4wZMaWDSY0RJz53WNnREXmcrqRdorQKKFBCz0iRuUcKadi2FQOr++1Jn44Oz9xZ93t0wM7T9tM6hwYSAWDiYX03O9qsylZ0FB+tfx1Mj9qU7az20+A84E72JUKAyA9bJ3c7vFDEddqg0UNIBCquIPU67PE4rhRDGBY=,iv:16uH+R88U5t3Kt1viWhMuvfk7q8Oqv198zOzqWQotIU=,tag:ZH77LA6OxdzJapeTj8wG0g==,type:str]
zigbee2mqtt.yaml: ENC[AES256_GCM,data:a0gZIxpx7TwOm8kVZKXi2JrqVFx9XRhhSp2cxncIYZ98w5+DvT71JjF7P+nHiAntCWnnqSssih1baxkTmn38PB9U9VeVNDi8Qu/YGSrKs6athtqVyemmbCsJpS0R,iv:KsE1i5WMwEMyMjKK1AtlGrMHuzHkJVn1dMIgg4tXwMA=,tag:Hbgo3EVY0loQmcEzRMs26w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m97ls72xcy8v492xrru4keyjve0jcqytqne6jk62zl72j3xsqgrql0ckw2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdUIwMlBNNEh3NEpmRW9O
            T2V6TFlsaWN0VUYzeGlFdHNnZXloTmF2Zml3CkRwQURhQkVVa1lwL093bnhGK085
            dkRpS3lwUjRuOThoWmVJclRSbnpRcncKLS0tIE04TWc3RFNTMVZ2ZU1YQjBrOURs
            Zkpsa3VDc1dxdk1yMlFhQ3RtcWVUVVEKJQa6c8GUx3vkpOa5EG9lIEJ8g5ZgqXuA
            Vqf6KcRYWAB81/agu0QLpAOf9c2/LfnaHj8aIU3peLeuGyw4RqqHRw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1c4zgcemg330ajaekh23c9v97ehv78auy338dr0tf06hst4p00g5scjlgah
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzOHhuTjdDRjdzNTBYZ2VS
            Slo3YktPQnJZQ1pyWkUxS2NZNkhWU0t6d1hFCjNPNElwYW92RXNkc0FGMHB5ZnBo
            a1B2aGpNSUdiTlV6SCtnRmRBQXNJN1EKLS0tIDZwTy9uZjVpUlUyWTRDa2s0YWdP
            NjV2ZGdoYUVOc1U3cFRtMWNZdXQwMk0KB6v6pn/ccfOyMKEXNIqJrMD1X+RjuQNp
            d46U9KvAKxNcpxANoLaVkbotqb/vtNfG+Nfum0JAobi8tXwYQ5P6Fg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hdpn83swtm7rr4ex4x6kh9k3ffqq23qug9n0ztq8wgaqlu02xekqku588k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TVRNQXMxTk1idllMbkMw
            K05qblBDRnJwNXJqSzZkeFhaeGNBcFh1OVNJCjNIR3ltZW9oQUhXQ0I2VzlPSktk
            UFl2Vyt3b29tcUxRdml4eXVOMTNQRFEKLS0tIFZFdTBtbENhb1NoNW1GRDFnN3Bh
            Smozd21yaFU5QXRaZDRWRHhOaWFRZTgKWQhoaXZo3YO8UQPOAMdC5t4WA2hKY0zL
            b8MrYL11S5h/HPKo3JT3uTwq1BXvruzYWXLNgyf4UnIHu2uZBFw35A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age102uzctt5y5qgqn9tz0njv0uh3f8yc7ssr3y8uxc3gd2n4lvu35es66euf4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4aUtiRGpjVjY3c2VNWU03
            d3E3TVduZGx2UjlXZ2QyUTAwK3ZHdll0R2xBCjdWdjQyVjZsNVZYNHVVWUN1UzlN
            T3p1bWhlOVpQclEyb3hVY0p6bmJudlkKLS0tIG5RenZ4U25KL1FpL01pZUNhdVQ3
            MFh0N2k0TWg0N09PaVF0SitDZHQ5KzAKgc9ivSQiv4lxj3B1DdY4pdnbsrvY3jog
            BkWOjJO2VyJTemNQuP//ALUtMHooZLIh8f2eZOaZCLEzat2sox2xig==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zmye9v3dmws9vtvkm8gfgknedggql0hnl74k427wqup9d0rq3esqfgthua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCN3NGM3hpUkRISlBFV0RT
            aWdoaC9ZYkxsSEU3RUR5UlphVFNoMVpFeWtZClNLWTJxTFlPN01aL0hhRHAycm91
            VjFwYnF2Y1Y5SjQrV24zU3d2eU82UWcKLS0tIHd5VkFCaEU0UDZxZ2dIMTErOGJj
            b1ozMHhPNHZjYmt6bWI1VytQcWg3WncKLeytMwhY9dWong83GWXTkBUgK7nKDrQe
            HQ17uXZKb4cLEI/1jeRfHnPXPPawMA6fv6sT3KQsDJLaPrErw5MSSA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mwrrymv9hsyhk3vtr5gqnhqg76rsh4f4gjpr5d3rg966lze6lc8s8x4z20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSE4xQ3VFNndLQlhtRkV4
            dWxqVDViaTZkODJwSXMzR2RteE9aNTQxQzJrCmU0NGo4TWt1YjBiNVU5MFBLSC9W
            eUZSU1ZWYTRMcDNTZTlEZnQyUE1BMlEKLS0tIGlhUGpTVlowMG1Jc1hhWjJieHox
            TlJjQkhXY0VaVTNkUXNSWjUyYnF0YW8K3CrVloNa038gZ+YDIuajSG+zS3/N1QYx
            9WGvC2I0L6lLtPBwAzqoGo4IgamRNUo0HxII4nwATAKP9qr2nYNgqw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1npj84lxnq72ppch90k7fw62wwy3wq90c03hy7r596m3yvyevd4sqlqma6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbVU5ZEE0VU1EVlJWNTQ4
            ZEYySTU1aTNKQm1MNmhJSW1DZ2JFeUE2VVdnCjYwVU94b0dGTEtTblk3VWNkTThm
            akZGTXlQMUJ3S1BNb0l4di9JRW5YRFkKLS0tIGFmS1IzZzNTdnZHdHlFNnNrdGtT
            ZmtOUHdzRUxUK1FvTE9qeUVuVWhFcUkKC2hfzwO/RMdE2x7N288XXhh89pXh+Qxz
            9qpEhU7oDwPGvpubr5aEixhgn49WOm40JwB7pAbdgE1BYXEvSJkA/g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1v808y4su2d9yehped4mahc2cgs56x9eeg7kgcwltg9k0vgqx8vxqrymgh3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRTBUZTZadzB4TkI5Z2VH
            N2J1anlTNnVNUHZVbmZ3OUZGUUFDUHVyeFVRClYzT1lDZU9lekRiQ0toRWhnOVB3
            dUNtQ1BhVnl4VHVJTElRTlA1OWk5dzQKLS0tIFJ6UGQ1YlJqNTFqUndEUlZuQnc3
            eE9JSTFaVm1paHpML1RWWlhvQWFqZnMKyAknA6fhKMxj468m3AK+Y5Tk8TDlxptk
            OlvTrP5epv86nKzJDnNn5bE989zYc2aVboQLoN0gs4GemHgOajhInw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1p2au0z6k7fnca8pl3p8px4ckt676ap43x78ud89ew5dux7p6r4yqhyqe6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUmludXdUOUxiY1pscHp6
            VkczbVBJQ0dQMm0yKzNodDZNVjlMazJYOVVFCjdtQXFnbUJsazRualphQ1Azck42
            TndNa2hiaE1uZWFOUjc3bzF4bUsrVTgKLS0tIGdxNFNGaTJ3Z2cySHlnS0h4dTBF
            WWhiUDU1aml6S2w0N2ZSR2xuTTBKWTAKOgxpkvJm0EiFOS/dpikbnlsj6Klc1lFd
            CKWHmezxsFM39HQDa0yXDLfH6H9yh86ySs/oIakdOYdXMVTSmt9e6Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age150kczuryvnf82cfwdrph7tekxctmwe2nnhmefw7gs6f6sl4n53ts5d7yve
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3c28yT0QyL3UveWxoOGZj
            L1duQ0dyZHBSLzBUT2E3MFFmN3ltelM5K0FRCnJ0VEJHUExJV0NQQnlCaVR3aXRE
            WTU3dXo2ZGFJRHdpZ01yLzJ0clZocmsKLS0tIEtpOGM2b1ZpZ0J1WlpuSUF0M1hY
            NVY0YVNMVVJVTGdCcFpNSmhxcE5GWDgKS7Hk8HcUCi7znzhMKWrVSchDKnLENcFC
            /kmxQhkb8TqA+kdjWMdG8n7vMsKQDpqu91aHCU8/G/xOgBQfnUzYog==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1klyhch983y7as7xnceltplys58lhmpu3w0qpy5gf0nmay6fjhadspml7nf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORkJZU0xGM05JQ2l2NWcx
            a2JyUTVVS2JpcTNRSDZ0eHR6dlpXc0x2bW5BCmpscGcwbm1sTHBmTGJ6U0RCV3F6
            NGtvV2s3amMrSDZLUVl1NklHdGxDcDAKLS0tIEtCcEJ1OGNTV3cxZ21rNk9ZZ1hK
            b0xoaHRwbit2RjZ5QjM5S2tNbU9zUTgKHflwvyfNpUbKU1pkoOO5qiVbVHhXlSmh
            SmZoWpIVTEwbpFiiSWWajPG9qqt/hyGZ3+TMa5k/Tm5kQFNaheT8eA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zr8jlq26nmm9v9heg2tv5gym87ctk7ry67x32zfux43ta75mrfkqmj748g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2U0YwMlBvVXVMbk5wNWdR
            N21mQld0S2hVenllc2Rrc3g5SVlaZlNiK0FnClVCRzlvcjNxbm4xVjJCd0hKODY3
            Wm9kM0U2UHg4VlVMbXZseW0yS2NxS1kKLS0tIHVYVUNxN2FVcVY5Q1FjMUpWdVUw
            Y3E3L3BXYUszV0FWUkFrVGpHcWkrZE0KjK8JAo63vD0Bnc9J9C0W2zRofxJ28wHc
            i3aK027Lxb5pqmiAOlU/MywHjcHK+v2UAKDdTDLZ4leKJ7EpWaQpig==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19e4mghy3fh2ejz64hc7038t5thjddwk5rjlad4wekg35cvyy5ses2ve9q8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2blZhSG5KZCtxdEZZU3Rs
            d0RmK1p2V1BJMCtVcTRsSXY4eVNqOWtsckdvCnZOOHdTRGhWc0NYOVdPWFFyMnI5
            c0JQZWx0WXpSckN3aE5JSUYwcjVBc3cKLS0tIGZMRjI5RWViYytLMkNqMzNOU3lu
            ZGhhZVJtR0RIaTd2VExpdjJOTnhTUkEKzryz7gVHN7NQMcDRaHEIJIFcyGFFjnzH
            4Rxtk2SpW+DpZVStxu9nUtMLX/8lMiRU2vxTaPWOmaHCfA4VRnh/Ig==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18jr3phuw28jkmhxg220nnvp5sev6fs623uxylhnmfsed73tg5pvqzmydem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WGxkdVdlYmhPdFNQd1lN
            MmUxczQzeHlMa3djZFdBZ1dpSXJkNzZxWlY0Ck5KNkpWSEVXaW95bWkzdGdocnl4
            TmR2bzg1dzRNWUdvRlVjeHpRUFYvdE0KLS0tIFFadWhzT1lETDAxM3NPcEJCaW1T
            R2puWjFWWklBL2Iyb01JWnkzZVZtMFUKuaJ1FlJ4oiiRiMUidwPJmwBbYyYzlvQ9
            +jF8G8Bl6XmcgCgcVqhGvnvA3KX90eMxonDKLlGQKNPiHBp2RzDWGQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1fcul2dn079vuw4jghlhyv075fq6qg3fmvkgdyaq3u2chwu3c3dqqw44hcn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNlhLQnp6cUdmS29XeWx4
            eW9kM0tlK3puanYxUWJnNk93U0p0TjJjdVdFCmlxMkx3aWRGSlFIRDk1UkhCQmk0
            VU9ZU0VhMklqbUxOY3c3RVBWYjJPeWsKLS0tIFUwS2d3ODVuYXNTZ3JNS1lyQXM1
            UE56d3U5Nmw5TEtJcUFqU1Rqa0pKRlUKBCYX8pkvIVw+bjGzjAISLwkLn2XiggYN
            flHToDaENO8L8fK5p4lxm5KUrafHMcQoN8lFKOKUBM8hao4fCn09NQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jxrv4vph55036gczwjulu4t0wp7tzacxtcjv9wfrve4fps3w7p2sds32s3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTUY3alVXaTlRVmlEcFdQ
            T0FIdGFQaFI1OFk5dXpqWFpybzQzVDM0RWtRCktUYlZxT09MU1k4WWc4bTVhcnJ6
            MktPcVNabkJHYk15NGtNWlkxU1hhSlUKLS0tIDFZbFgwb2tsZ0MzZXByd3gyTXhW
            Ui9DWS8xYXpjYW1wMlYzWFhaU1U3WW8KsM+kX1m3TCHn6ax9P44FpNKhpTkLu0Il
            zw/bmsbgBjE2mB6M4fkmiZ7++0Ol68PqkVwU9p3y5CVfpsP4U0BpLg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1swykyyzngx7zs4ttt6t32ru8yfg3gq3gamfc4ywzdwfdnjn5fqesxqk440
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOK3FvMTdGeDhNTFJOZEpy
            ZWwrOE9OeVN4emJXL3JsQXQ5YXBHWERqdkY0Cm1Fb3hETHh2OXdKVzUvRjJwL2V6
            UkYzT05sQW9jRXRFczNMYXFNRXdhV0kKLS0tIDRjN0NGSW9QcE9JOG5URUFtY2d4
            b0R0NXVIby8vM3lSaXZTSlpVMWFCOUUKjjp+oFx1ZcmYmCLm4xYO5E+JqmKCkF4n
            caDgrziEpp4+fgPgOl8nBbeNZahAA8egrCwznwAO8Pk/u8Ig4tNRnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-06T16:10:39Z"
    mac: ENC[AES256_GCM,data:qxcZrFAi2LiEoM3tpD4fMlgRlBJgibADBWfJVLQy9mtnSlwU7ZQ2cKeplzKd/EthjnBXYbPYA6XlKAJJahB+YX8XrqgJkdplzc9tOtAvO1UxviMpqkKZMTgfXiv25YzeR8CVGRJBdnlX+rmlbIc9vxZNoWaKj3e4KqlFzezzVcM=,iv:dQ8RkflHWfGCqjPD/iLp99w1LFxKoLokGIToQZ4ExzY=,tag:NYrhwyUmIXFsewT4ToBwnQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
