attic_secret: ENC[AES256_GCM,data:yV67At8h1uQfNNMU0nkADVXxTPjO0om5kiqroF9KhUn6NajCnJt96UiGO7v45Rq4mpGjnxHXXmVk6HQ6IeugRSawsdA6Ltw3OzBw+oRipJU4220v7PdQjtdS8CVIW8C3TO/Tv6y8pXdGCYAg//bodbwdp4W/qoZ/NcbMQ+K5/L178D+4R/1a9teRGHTqs5BQkWbNuXbE9YFrhMEimhXD3ftnd8DdA7nxgwxITVxuP0352Wcc1JOes63zVOGA1ueK5+Cua0o9+TACLuXBHK2yEJE4Pqg=,iv:G/jYx9FezIsFuCRhnSut6/dkKGgkViAzqjL9fITi9T0=,tag:76wTtQ4IFqiisy8ZYMUgXg==,type:str]
cloudflare: ENC[AES256_GCM,data:Pklel78jbLm/aKRfg8AMaYVjrS9lXhYrq1kTocE/qhodJvrOjI5vDazERq4+FAPeBJgmS/FrJ6VyTWrcKSSUv90pQqU5adPsBIJz4yLKnjKO5wlPfuu7/oTgGRhXgwRs,iv:ajIm7dB10aVDzfL7npvFLudQsbs2WAtY2/fvjk7NzJY=,tag:JK8E1DzRb+CuydNrh1krfQ==,type:str]
jellyplex_creds: ENC[AES256_GCM,data:JyODs8Kslo4ZNFNS4FLQs1sKWKljWDJ7U8uXZpeFsVWX8aFQebo61yl58/KQ4qtuv1PBOFL5e44G2iPVqC/dbPqoddOYDyjwQEMOPfmp7H/wqsSK,iv:6a+5rFrXTCFMbK06tQ+TZ0S0W2sqJ2HMHvs36ef8cDA=,tag:GIXPGfRkbTFn//SbJPrrCQ==,type:str]
miniflux_creds: ENC[AES256_GCM,data:wW9eabECcE6TFSrgzMbNAfHlOBaqARLbhUC2NSYUxvn2zb7PaU6WOyVNLQHI8K23amna/guX8eu9E4oc48N+PgwkmpkpqniWCwoHn3ftD/aj48o=,iv:D2lw+AHCPSvqZLiob8RbulqNM5mH0feqHRfEOjUo8oY=,tag:g6nG8BPKVafxKgaeaOSvGw==,type:str]
couchdb_admin: ENC[AES256_GCM,data:bhlkqSqrbHOXHsdvsEOQ2LuRhqFCx7iTgiSHogs5t0j/D6Srlpy4OdpNYxRxNfMZx6taPYrAIJbC,iv:I3N+i08oHmd+STkSzKmcE7oDiCcCyrFHQIEIskN7g14=,tag:YtJhLZqt7tHzQ8lBVdAY/A==,type:str]
ts_key: ENC[AES256_GCM,data:9Por9DsQTsopx7kh1IrYOK7BLD6kRhRLr8I9kpOgq0oRUXo4j3AJCgekvGUbfX6peXYZW5BS6/U=,iv:TUhmx2j0mZlxw5aTFALlZhGdNClStqOTe/mp1n7mIAY=,tag:gv1m2hjWFDCLXGJ2tuM9bg==,type:str]
vault_unseal: ENC[AES256_GCM,data:Mm18BQ5+bA3Oo48kDjvGlSRnZ04SIavxl3i4eIEDClmSjvqB8kW2pnqfW4wZMaWDSY0RJz53WNnREXmcrqRdorQKKFBCz0iRuUcKadi2FQOr++1Jn44Oz9xZ93t0wM7T9tM6hwYSAWDiYX03O9qsylZ0FB+tfx1Mj9qU7az20+A84E72JUKAyA9bJ3c7vFDEddqg0UNIBCquIPU67PE4rhRDGBY=,iv:16uH+R88U5t3Kt1viWhMuvfk7q8Oqv198zOzqWQotIU=,tag:ZH77LA6OxdzJapeTj8wG0g==,type:str]
zigbee2mqtt.yaml: ENC[AES256_GCM,data:Ov0re5O4XWtTIkHCkGpkGMCU5U3LmERoaQkVK8wUeh49VIGoW8lKr4IUWTlXy6aLSHo97WcBAaNh9yD0RDeZ,iv:0mbIi3TaC27+b4rNfUvlz+S0WfMq6FRLWgXseU0tg+c=,tag:WANGCT9EBWCCSys1fT/vUQ==,type:str]
pushover: ENC[AES256_GCM,data:K7h1jfF+XpsGVE7RA7RSYpQ9+lItcY2C9nD6cy3Dhl4Yby4bdfmZ2T/sxDe4+ZTncC5Q0AbMJchoo9nNlnyG9VWM2Y1LZDdtGx4zaKR+OkaeCxTbDvfued2n0hI7POQATz55weDqALlMJUp62jExZ4AqUpJE+6IDk12Yc0myoQ==,iv:1ENakF+h2Sqri2oOAj7VG5GbwlkuvvVqqCoxDbGFbDU=,tag:oL5agYAAMqiselpp8Sm5Nw==,type:str]
frigate: ENC[AES256_GCM,data:JUdZOPvg5tJpNUwso5jqn8MDrhF5dPXp1mvsTBWFN2vklJ5p5PvgpRaaLxmrBcvjeh2Ox+8kNFEVFxKni9xanNJcr2Zz/w==,iv:JviqtSsoR1h/Sh17dtGPnyfQxorZBFnXXLecyiJe6Ow=,tag:/BEfLnDflrEd45APCJC52g==,type:str]
mosquitto: ENC[AES256_GCM,data:kDf2NHh4ACoHkAzXyAMsetjVknHVaqadqDDKQBw5cbQawuTukWdUhzmORkUODTr9+FhTjLNFwe9srzyeOmqU6BaAEkFujAUjWL9MGbqzCqlAgJv+9Kc43N6w4nheqf1gaou3FuL+hi8BBUPtMnsX+Xs=,iv:wzcbeMpRO8xaOdcLx13XV62YEgWKtYihK22QcjK9VSk=,tag:FDdUIbVDFuoYslZpK9VL1A==,type:str]
hercules_join: ENC[AES256_GCM,data:qPmFPYFKaGq1k7BuyPAWCatzYwRkuPNzkA6ZDTJJ5080Q7LZoRdpDIJQnPJdZXfg3neENFnSE0q84G2cDNHxig7m4Tfy7cjYjVwANBNdrtZMuD3X1K3bnjWkvSProFi2UyU1pxuFJYZXxFt/Uj0QavoIP2WhAOV0Pd3SROh1Rd6xItewZhm3Wi23P8S7i87EyKN5UpLmBNB9xp1lPS8lLQeFAWJJL00sfhUxj8lT7N7UCyMqZ94W8PJlj7rQW7qejwLtxwi9qIJWP7HYabi8t5rJrDb0m5XqGmwgzI9kKQHFqVMs/o4SZ8ESPOo=,iv:DmX+qRnmxnr/zYh+6ZNhpFm2GajjjOygrkU5UD8yARY=,tag:Vu6J9yE2IinnVT+dh9c80Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m97ls72xcy8v492xrru4keyjve0jcqytqne6jk62zl72j3xsqgrql0ckw2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdnkyL25OOXdpZFhpOFd6
            eFlPenBxV1ptVVdRZ1dxZHBxU216WG9IYkU0CnlEd0VLZVpzNEswbDQzVGs4YmhZ
            VVA2R3p0cWlKeittTHdYclJtdWd6ZEkKLS0tIFpQT2tkdGlWWUUwR3dNYjcvd29I
            WlpXa1Avd1VQc3ZETHQyYmxqL2FaMzgKv+2P+0y4GUW0wGN+Q1awqJ9xJHDuB0na
            NOwFUkVc8wLQJtHDEvD50q8GfKER31gScEdstIhCrV8hXd94Xyu8Pg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mwrrymv9hsyhk3vtr5gqnhqg76rsh4f4gjpr5d3rg966lze6lc8s8x4z20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieFdVOHQwbTFiZU82TDRt
            UGszZkY2dVlPMjZ6Skt1aVFYcFE1ZWh0MkNRCmw4aWFMTVBxVnBqelZtbU9KdklL
            S1dYVTV1MFBmdWFVVjNYQklqYzRBbFUKLS0tIEFDYTZXdVZOUlc5NzhQeTJTUWVK
            TURvOHhGR2U0THB3Z2MrTTF0MUtkVXMKvusBADVW85t/h4fb8uYNERvvDddz5Jqq
            HLDLhs1UQ2fs0rmGps55Hi3dN9THuEIkwku7sC6Bio0k0kE//EuJuQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1klyhch983y7as7xnceltplys58lhmpu3w0qpy5gf0nmay6fjhadspml7nf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoV2NzeXZ5dTc3dmVySi9z
            YTlDVE5mVmRiSW1zaW9oRnlNNUpWd1BrZjN3Cm5xVFo5aEY3aFg4K1N4aVE3elp0
            UjlydUU2SG1KVVRkYW9raHlvRHdXcE0KLS0tIEt4aFNZcm9QMU4xN1VKQzRJRW5p
            YkZaRXlVSUxLSHZ6eE55T0pQQnE4Z2sKTg916UkyoVji+RQQweUWGudDe+Mgl22O
            8wlcTMBHcKYto/EVGAyxw/Ut0/ky/zlRiDGzuaLPaVFt9uHLenm2kw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1swcq9xcguv3t2tgna80hewemc7yg0cdgyjff86q0d6gj24j8xuzshl2pdy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVLzNqa1hpcSsrOTNIUmNn
            bUJ4ZkI0MFh1eWk2Z2dFVXRHMDZiZ2orK0N3CkJHNFRPYVMxbXcwMFRJTm5zREln
            RXFFTTFsa0VIK3l0bnpXd2taVER0MjQKLS0tIDgyQ05ZQXVENzJhaEVpTjBEWGJE
            dkJpeWF0MGM3L0pURU4wZWxQdXk3dEkK1ZmA0ALo+HyrKJR/rv2VIBEaT/kzZrbh
            eScZPh6lk/ewCKG3N02iNQe1T30gmPi2f54cb2nm5Zo+Sezbi/iAiw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zr8jlq26nmm9v9heg2tv5gym87ctk7ry67x32zfux43ta75mrfkqmj748g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZHU4ZXZ4MUo1NnRNRWFk
            Tm1wdmxaUGdDWC9OSFFGUEFZYXZrem5jRlg0CjdLeHI5SW1IbE4wbnRKeDNIeE9t
            VkI2VFppNUo1OVh0ZXpRSEcxQUpTSFkKLS0tIFFlNnZOOFVqMTZOdjZCWU8xb09o
            SVp5T3pkTE5FdjVIbkRMVEw2NW11K1EKFhBS8dszDxhwgO6RBMu12pdxd0xCANXX
            QHhGWMEZv7alq/V0Us7d08d2ym21bvHfqRHQN67edvoczqkoQJk9qg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age154w9fxzva5uy9qzj0nc9002mrlaprnvqml63kmhn2c8c8sfk5swq9hgxnh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbDk1ZThOYjkzVzBQTi9u
            a3IzakZjSVZlczlMRW4waDNrSmt3ZndGUDJvCmdUc0lrRUlHcE15TkNIN3g5RWhZ
            ajhqOHI5Mmd3ZGVQUndUbU9FL2JLTHMKLS0tIG96OXEvSDFuRy96N3VsWXZqd0Zo
            U0JSNjl6cXpkS01HeXZ0SEZzSFRTSkkK5CkjHFjDioiiyeeCQ5KRsqzdqPHOv66l
            IQcBuyEUuEEs+1R28/i03uwE1/R19IcyjHKcQIvB24R5zRgSrbRy5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-07T00:43:32Z"
    mac: ENC[AES256_GCM,data:ecr03kOLCxh8LbKKe283166irwJqvrrXjVz94df+TsZrEkQf3kCdUT+rQIzY6sv5uKzddFNCEEo7sMtFoOqiizeIgRQMJc96D48O93BjDWZJ321Ck+UPn+NQCb8I2oEt0PUr7GToUTRmIA02THbGF2I9dMXfu6M6KJVDXZLHBjg=,iv:ntkMfcWD451KBM6LkBSX4zPT6XjpTbXqpUmTshzQgf4=,tag:s9JMPUMqfhsO52TH9qW/9g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
